// Package wrapper provides secure wrapper script generation for Claude Code execution.
package wrapper

import (
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"strings"

	kairoerrors "github.com/dkmnx/kairo/internal/errors"
)

const (
	windowsGOOS = "windows"
)

// CreateTempAuthDir creates a private temporary directory for storing auth files.
func CreateTempAuthDir() (string, error) {
	authDir, err := os.MkdirTemp("", "kairo-auth-")
	if err != nil {
		return "", kairoerrors.WrapError(kairoerrors.FileSystemError,
			"failed to create temp auth directory", err)
	}

	if err := os.Chmod(authDir, 0700); err != nil {
		_ = os.RemoveAll(authDir)

		return "", kairoerrors.WrapError(kairoerrors.FileSystemError,
			"failed to set auth directory permissions", err)
	}

	return authDir, nil
}

// WriteTempTokenFile creates a temporary file with the API key content.
func WriteTempTokenFile(authDir, token string) (string, error) {
	if token == "" {
		return "", kairoerrors.NewError(kairoerrors.ValidationError,
			"wrapper: token cannot be empty")
	}

	f, err := os.CreateTemp(authDir, "token-")
	if err != nil {
		return "", kairoerrors.WrapError(kairoerrors.FileSystemError,
			"failed to create temp token file", err)
	}

	if _, err := f.WriteString(token); err != nil {
		_ = f.Close()

		return "", kairoerrors.WrapError(kairoerrors.FileSystemError,
			"failed to write token to temp file", err)
	}

	if err := f.Close(); err != nil {
		return "", kairoerrors.WrapError(kairoerrors.FileSystemError,
			"failed to close temp token file", err)
	}

	if err := os.Chmod(f.Name(), 0600); err != nil {
		return "", kairoerrors.WrapError(kairoerrors.FileSystemError,
			"failed to set temp file permissions", err)
	}

	return f.Name(), nil
}

// EscapePowerShellArg escapes a string for use as a PowerShell argument.
func EscapePowerShellArg(arg string) string {
	arg = strings.ReplaceAll(arg, "`", "``")
	arg = strings.ReplaceAll(arg, "$", "`$")
	arg = strings.ReplaceAll(arg, "\"", "\\\"")
	arg = strings.ReplaceAll(arg, "'", "''")
	arg = strings.ReplaceAll(arg, "&", "`&")
	arg = strings.ReplaceAll(arg, ";", "`;")
	arg = strings.ReplaceAll(arg, "|", "`|")
	arg = strings.ReplaceAll(arg, "%", "``%")
	arg = strings.ReplaceAll(arg, "\n", "`n")
	arg = strings.ReplaceAll(arg, "\r", "`r")
	arg = strings.ReplaceAll(arg, "\t", "`t")
	arg = strings.ReplaceAll(arg, "\b", "`b")
	arg = strings.ReplaceAll(arg, "\x00", "`0")

	return "'" + arg + "'"
}

type ScriptConfig struct {
	AuthDir    string
	TokenPath  string
	CliPath    string
	CliArgs    []string
	EnvVarName string
}

func GenerateWrapperScript(cfg ScriptConfig) (string, bool, error) {
	if cfg.TokenPath == "" {
		return "", false, kairoerrors.NewError(kairoerrors.ValidationError,
			"wrapper: token path cannot be empty")
	}
	if cfg.CliPath == "" {
		return "", false, kairoerrors.NewError(kairoerrors.ValidationError,
			"wrapper: CLI path cannot be empty")
	}

	envVar := "ANTHROPIC_AUTH_TOKEN"
	if cfg.EnvVarName != "" {
		envVar = cfg.EnvVarName
	}

	isWindows := runtime.GOOS == windowsGOOS

	f, err := os.CreateTemp(cfg.AuthDir, "wrapper-")
	if err != nil {
		return "", false, kairoerrors.WrapError(kairoerrors.FileSystemError,
			"failed to create temp wrapper script", err)
	}

	scriptContent := generateScriptContent(isWindows, envVar, cfg)

	if _, err := f.WriteString(scriptContent); err != nil {
		_ = f.Close()
		_ = os.Remove(f.Name())

		return "", false, kairoerrors.WrapError(kairoerrors.FileSystemError,
			"failed to write wrapper script", err)
	}

	if err := f.Close(); err != nil {
		_ = os.Remove(f.Name())

		return "", false, kairoerrors.WrapError(kairoerrors.FileSystemError,
			"failed to close wrapper script", err)
	}

	if isWindows {
		ps1Path := f.Name() + ".ps1"
		if err := os.Rename(f.Name(), ps1Path); err != nil {
			_ = os.Remove(f.Name())

			return "", false, kairoerrors.WrapError(kairoerrors.FileSystemError,
				"failed to rename wrapper script", err)
		}

		return ps1Path, true, nil
	}

	if err := os.Chmod(f.Name(), 0700); err != nil {
		_ = os.Remove(f.Name())

		return "", false, kairoerrors.WrapError(kairoerrors.FileSystemError,
			"failed to make wrapper script executable", err)
	}

	return f.Name(), false, nil
}

func generateScriptContent(isWindows bool, envVar string, cfg ScriptConfig) string {
	if isWindows {
		return generateWindowsScript(envVar, cfg)
	}

	return generateUnixScript(envVar, cfg)
}

func generateWindowsScript(envVar string, cfg ScriptConfig) string {
	var sb strings.Builder
	sb.WriteString("# Generated by kairo - DO NOT EDIT\r\n")
	sb.WriteString("# This script will be automatically deleted after execution\r\n")
	sb.WriteString(fmt.Sprintf("$env:%s = Get-Content -Path %q -Raw\r\n", envVar, cfg.TokenPath))
	sb.WriteString(fmt.Sprintf("Remove-Item -Path %q -Force\r\n", cfg.TokenPath))
	sb.WriteString(fmt.Sprintf("& %q", cfg.CliPath))
	for _, arg := range cfg.CliArgs {
		sb.WriteString(fmt.Sprintf(" %s", EscapePowerShellArg(arg)))
	}
	sb.WriteString("\r\n")

	return sb.String()
}

func generateUnixScript(envVar string, cfg ScriptConfig) string {
	var sb strings.Builder
	sb.WriteString("#!/bin/sh\n")
	sb.WriteString("# Generated by kairo - DO NOT EDIT\n")
	sb.WriteString("# This script will be automatically deleted after execution\n")
	sb.WriteString(fmt.Sprintf("export %s=$(cat %q)\n", envVar, cfg.TokenPath))
	sb.WriteString(fmt.Sprintf("rm -f %q\n", cfg.TokenPath))
	sb.WriteString("exec " + fmt.Sprintf("%q", cfg.CliPath))
	for _, arg := range cfg.CliArgs {
		sb.WriteString(" " + fmt.Sprintf("%q", arg))
	}
	sb.WriteString("\n")

	return sb.String()
}

// ExecCommand wraps exec.Command for testability.
func ExecCommand(name string, arg ...string) *exec.Cmd {
	return exec.Command(name, arg...)
}
