package wrapper

import (
	"strings"
	"testing"
)

func TestGenerateWindowsScript_BasicOutput(t *testing.T) {
	cfg := ScriptConfig{
		AuthDir:    t.TempDir(),
		TokenPath:  `C:\temp\token`,
		CliPath:    `C:\Program Files\Claude\claude.exe`,
		CliArgs:    []string{"--help"},
		EnvVarName: "ANTHROPIC_AUTH_TOKEN",
	}

	script := GenerateWindowsScript("ANTHROPIC_AUTH_TOKEN", cfg)

	if !strings.Contains(script, "# Generated by kairo") {
		t.Error("Script should contain header comment")
	}
	if !strings.Contains(script, "$env:ANTHROPIC_AUTH_TOKEN") {
		t.Error("Script should set environment variable")
	}
	if !strings.Contains(script, "Get-Content") {
		t.Error("Script should use Get-Content to read token")
	}
	if !strings.Contains(script, "Remove-Item") {
		t.Error("Script should remove token file")
	}
	if !strings.Contains(script, "C:\\\\temp\\\\token") {
		t.Error("Script should contain token path (with escaped backslashes)")
	}
}

func TestGenerateWindowsScript_WithSpecialCharacters(t *testing.T) {
	cfg := ScriptConfig{
		AuthDir:    t.TempDir(),
		TokenPath:  `C:\temp\token`,
		CliPath:    `C:\Program Files\Claude\claude.exe`,
		CliArgs:    []string{"--prompt", "Hello $HOME and \"quotes\"", "--model", "sonnet-4"},
		EnvVarName: "ANTHROPIC_AUTH_TOKEN",
	}

	script := GenerateWindowsScript("ANTHROPIC_AUTH_TOKEN", cfg)

	if !strings.Contains(script, "`$HOME") {
		t.Error("Script should escape dollar sign in $HOME")
	}
	if strings.Contains(script, "$HOME") && !strings.Contains(script, "`$HOME") {
		t.Error("Dollar sign should be escaped")
	}
	if !strings.Contains(script, `\"quotes\"`) {
		t.Error("Script should escape double quotes properly")
	}
}

func TestGenerateWindowsScript_WithDollarVariables(t *testing.T) {
	cfg := ScriptConfig{
		AuthDir:    t.TempDir(),
		TokenPath:  `C:\temp\token`,
		CliPath:    `C:\Program Files\Claude\claude.exe`,
		CliArgs:    []string{"--prompt", "Price is $price, total is $total"},
		EnvVarName: "ANTHROPIC_AUTH_TOKEN",
	}

	script := GenerateWindowsScript("ANTHROPIC_AUTH_TOKEN", cfg)

	if !strings.Contains(script, "`$price") {
		t.Error("Script should escape $price variable")
	}
	if !strings.Contains(script, "`$total") {
		t.Error("Script should escape $total variable")
	}
}

func TestGenerateWindowsScript_WithEnvVars(t *testing.T) {
	testCases := []struct {
		name     string
		envVar   string
		expected string
	}{
		{"custom env var", "MY_API_KEY", "$env:MY_API_KEY"},
		{"anthropic default", "ANTHROPIC_AUTH_TOKEN", "$env:ANTHROPIC_AUTH_TOKEN"},
		{"openai style", "OPENAI_API_KEY", "$env:OPENAI_API_KEY"},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			cfg := ScriptConfig{
				AuthDir:    t.TempDir(),
				TokenPath:  `C:\temp\token`,
				CliPath:    `C:\claude.exe`,
				CliArgs:    []string{"--help"},
				EnvVarName: tc.envVar,
			}

			script := GenerateWindowsScript(tc.envVar, cfg)

			if !strings.Contains(script, tc.expected) {
				t.Errorf("Script should set %s, got: %s", tc.expected, script)
			}
		})
	}
}

func TestGenerateWindowsScript_CRLFLineEndings(t *testing.T) {
	cfg := ScriptConfig{
		AuthDir:    t.TempDir(),
		TokenPath:  `C:\temp\token`,
		CliPath:    `C:\claude.exe`,
		CliArgs:    []string{"--help"},
		EnvVarName: "ANTHROPIC_AUTH_TOKEN",
	}

	script := GenerateWindowsScript("ANTHROPIC_AUTH_TOKEN", cfg)

	if !strings.Contains(script, "\r\n") {
		t.Error("Windows script should use CRLF line endings")
	}
}

func TestGenerateWindowsScript_WithEmptyArgs(t *testing.T) {
	cfg := ScriptConfig{
		AuthDir:    t.TempDir(),
		TokenPath:  `C:\temp\token`,
		CliPath:    `C:\claude.exe`,
		CliArgs:    []string{},
		EnvVarName: "ANTHROPIC_AUTH_TOKEN",
	}

	script := GenerateWindowsScript("ANTHROPIC_AUTH_TOKEN", cfg)

	if !strings.Contains(script, "& ") {
		t.Error("Script should contain command invocation")
	}
}

func TestGenerateWindowsScript_WithPathContainingSpaces(t *testing.T) {
	cfg := ScriptConfig{
		AuthDir:    t.TempDir(),
		TokenPath:  `C:\Users\John Doe\AppData\Local\token`,
		CliPath:    `C:\Program Files\Claude\claude.exe`,
		CliArgs:    []string{"--output", `C:\Users\John Doe\Documents\result.md`},
		EnvVarName: "ANTHROPIC_AUTH_TOKEN",
	}

	script := GenerateWindowsScript("ANTHROPIC_AUTH_TOKEN", cfg)

	if !strings.Contains(script, "Program Files") {
		t.Error("Script should handle paths with spaces")
	}
}
