version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: kairo
    binary: kairo
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    flags:
      - -trimpath
      - -tags=osusergo,netgo
    ldflags:
      - -s -w
      - -X github.com/dkmnx/kairo/internal/version.Version={{.Tag}}
      - -X github.com/dkmnx/kairo/internal/version.Commit={{.Commit}}
      - -X github.com/dkmnx/kairo/internal/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - id: kairo
    formats: ["tar.gz", "zip"]
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - src: LICENSE
        dst: LICENSE
      - src: README.md
        dst: README.md

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

snapshot:
  version_template: '{{ .Version }}-next'

changelog:
  # Disable auto-generated changelog since CHANGELOG.md is maintained manually
  disable: true

release:
  draft: true
